---
abstract: 'Base class for injecting distributions into CPAN sources'
author:
  - 'The C<author> accessor returns the CPAN id for the default author which'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Remove: 0.34
  Test::More: 0.42
  Test::Script: 1.02
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Inject
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  CPAN: 1.36
  CPAN::Checksums: 1.05
  File::Basename: 2.6
  File::Copy: 2.02
  File::Path: 1.00
  File::Spec: 0.80
  File::chmod: 0.30
  File::stat: 1.00
  Params::Util: 0.21
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/CPAN-Inject
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/CPAN-Inject
version: 1.13
